version: '3.7'

services:

  db:
    volumes:
      - voldb:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - api
      - frontend
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx/svgs:/svgs

  backend:
    command: bash -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/project
      - ./utils/annotation:/project/annotation

  frontend:
    container_name: frontend
    depends_on:
      - backend
      - api
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend/src:/project/src
      - ./frontend/public:/project/public
    networks:
      - net-tier
    ports:
      - "127.0.0.1:81:81"

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./utils/mockData/data:/var/lib/neo4j/import/
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"

  api:
    container_name: api
    build: ./api
    volumes:
      - ./api/src:/project/src
    command: npm run start
    networks:
      - net-tier

volumes:
  voldb:
