version: '3.7'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      ENVSUBST_VARS: SERVER_NAME
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - letsencrypt:/etc/letsencrypt

  api:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    command: yarn start

  neo4j:
    restart: unless-stopped

volumes:
  letsencrypt:

