version: '3.7'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - api
      - frontend
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx/svgs:/svgs
    networks:
      - frontend-network

  frontend:
    container_name: frontend
    depends_on:
      - api
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend/src:/project/src
      - ./frontend/public:/project/public
    networks:
      - frontend-network
    ports:
      - "127.0.0.1:81:81"

  neo4j:
    image: neo4j:4.1.0
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ${NEO4J_IMPORT_DATA_PATH}:/var/lib/neo4j/import/
      - ./neo4j/data:/var/lib/neo4j/data/
      - ./neo4j/plugins:/plugins
    networks:
      - db-network
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"

  api:
    build: ./api
    environment:
      - NODE_ENV=develop
    volumes:
      - ./api/src:/project/src
    command: yarn develop

networks:
  frontend-network:
    driver: bridge
