version: '3.7'

services:
  nginx:
    container_name: nginx
    networks:
      - nginx-network

  neo4j:
    container_name: neo4j
    environment:
      - NEO4JLABS_PLUGINS=["apoc"] 
    networks:
      - db-network

  api:
    container_name: api
    networks:
      - nginx-network
      - db-network

networks:
  db-network:
    driver: bridge
  nginx-network:
    driver: bridge
