version: '3.7'

services:
  db:
    restart: always

  backend:
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    restart: always

  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/ssl:/ssl:ro

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_read__only=true
    ports:
      - "7474:7474"

