version: '3'

services:

  db:
    volumes:
      - voldb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/svgs:/svgs

  backend:
    command: bash -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/project
      - ./utils/annotation:/project/annotation

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/src:/project/src
      - ./frontend/dist:/project/dist
      - ./frontend/test:/project/test
    networks:
      - net-tier

volumes:
  voldb:
