version: '3.7'

services:
  nginx:
    build: nginx
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx/svgs:/svgs

  frontend:
    container_name: frontend
    depends_on:
      - api
    build: ./frontend
    command: npm run serve
    volumes:
      - ./frontend/src:/project/src
      - ./frontend/public:/project/public
    networks:
      - nginx-network
    ports:
      - "127.0.0.1:81:81"

  api:
    env_file: .env
    environment:
      - NODE_ENV=develop
    volumes:
      - ./api/src:/project/src
    command: yarn develop

  neo4j:
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4j/plugins:/plugins
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
