version: '3'

services:

  db:
    volumes:
      - voldb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build:
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/svgs:/svgs

  backend:
    volumes:
      - ./utils/annotation:/project/annotation

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: ./frontend
    command: npm run dev
    networks:
      - net-tier

volumes:
  voldb:
