version: '3.7'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: shan@chalmers.se
      ENVSUBST_VARS: SERVER_NAME
      SERVER_NAME: metatlas.csbi.chalmers.se
    volumes:
      - letsencrypt:/etc/letsencrypt

  neo4j:
    restart: unless-stopped
    container_name: neo4j
    build: ./neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    command: neo4j
    ports:
      - "7687:7687"

  api:
    restart: unless-stopped
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile.prod
    environment:
      - ENVIRONMENT=production
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NODE_ENV=production
    command: yarn start

volumes:
    letsencrypt:

