version: '3'

services:
  db:
    restart: always

  backend:
    restart: always

  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile-prod
    volumes:
      - /var/ssl:/ssl:ro
