version: '3'

services:
  db:
    restart: always

  backend:
    restart: always
    volumes:
      - backend:/project

  frontend:
    command: npm run build
    volumes:
      - frontend:/project

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile-prod
    volumes:
      - backend:/backend:ro
      - frontend:/frontend:ro
      - /var/ssl:/ssl:ro

volumes:
  frontend:
  backend:
