backend:
  restart: always
  build: ./hma_backend
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: backend.env
  command: /usr/local/bin/gunicorn -c gunicorn.conf runserver:app

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - backend
  links:
    - backend:backend

postgresData:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  env_file: postgres.env
  volumes_from:
    - postgresData
  ports:
    - "5432:5432"
