version: '3.7'

services:
  nginx:
    container_name: nginx
    depends_on:
      - api
    networks:
      - nginx-network

  api:
    container_name: api
    build: api
    env_file: .env
    depends_on: 
      - neo4j
    networks:
      - nginx-network
      - db-network

  neo4j:
    container_name: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4JLABS_PLUGINS=["apoc"]
    build:
      context: neo4j
      args:
        NEO4J_USERNAME: ${NEO4J_USERNAME}
        NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    networks:
      - db-network

  ftp:
    container_name: ftp
    build:
      context: ftp
      args:
        FTP_USER_HOME: ${FTP_USER_HOME}
    environment: 
      - PUBLICHOST=${SERVER_NAME}
      - FTP_USER_NAME=${FTP_USER_NAME}
      - FTP_USER_PASS=${FTP_USER_PASS}
      - FTP_USER_HOME=${FTP_USER_HOME}
    ports:
      - "21:21"
      - "30000-30009:30000-30009"

networks:
  db-network:
    driver: bridge
  nginx-network:
    driver: bridge
