version: '3'

services:
  db:
    container_name: db
    image: postgres
    networks:
      - net-tier

  nginx:
    container_name: nginx
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net-tier

  backend:
    container_name: backend
    depends_on:
      - db
    env_file:
      - postgres.env
    build: ./backend
    command: bash -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    networks:
      - net-tier

networks:
  net-tier:
    driver: bridge
