version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/prod.Dockerfile
      args:
      - VUE_APP_FTP_SERVER=${SERVER_NAME}
      - VUE_APP_SVGMAPURL=https://${SERVER_NAME}/api/v2/svg
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - SERVER_NAME=${SERVER_NAME}
      - IP_FILTER=${IP_FILTER}
      - ENVSUBST_VARS=SERVER_NAME IP_FILTER
    volumes:
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 1.5G
        limits:
          cpus: '0.30'
          memory: 2G

  api:
    environment:
      - NODE_ENV=production
    command: yarn start
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: '0.35'
          memory: 2.5G
        limits:
          cpus: '0.40'
          memory: 3G

  neo4j:
    environment:
      - NEO4J_dbms_transaction_timeout=15s
      - NEO4J_dbms_memory_heap_initial__size=5G
      - NEO4J_dbms_memory_off__heap_max__size=8G
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: '1.00'
          memory: 9G
        limits:
          cpus: '1.15'
          memory: 10G
    ulimits:
      nofile:
        soft: 80000
        hard: 90000

  ftp:
    environment:
      - FLAGS=-Y 1
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 150M
        limits:
          cpus: '0.10'
          memory: 200M

volumes:
  letsencrypt: