swagger: "2.0"
info:
  description: "Metabolite Atlas can be accessed programmatically using this web API. Here we provide endpoints to get global information on the list of models integrated in Metabolic Atlas and to retrieve bulk or details information on those models. The API is still under developpment and might change without notice.\n\nUse model.short_name attribute (e.g. \"Yeast-GEM\", \"Human-GEM\") or model.database attribute as model parameter."
  version: "2.0"
  title: "Metabolic Atlas API"
  termsOfService: "https://metabolicatlas.org/about"
  contact:
    email: "contact@metabolicatlas.org"
  license:
    name: "GPL version 3"
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
basePath: "/api/v2"
tags:
- name: "Integrated models"
- name: "Compartments"
- name: "Genes"
- name: "Metabolites"
- name: "Reactions"
- name: "Subsystems"
- name: "Interaction Partners"
- name: "Miscellaneous"
paths:
  /repository/integrated_models:
    get:
      tags:
      - "Integrated models"
      summary: "List all integrated GEMs."
      description: "Retrieve a list of all GEMs (Genome-Scale
        Metabolic Models) that Metabolic Atlas integrates. These GEMs are
        available through tools like GEM Browser, Map Viewer and Interaction
        Partners. The list is returned in JSON format. <br /><br />
        Required parameters: None"
      operationId: "integratedModelListing"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
  /repository/integrated_models/{name}:
    get:
      tags:
      - "Integrated models"
      summary: "Get information for a given GEM."
      description: "Retrieve information for a given GEM (Genome-Scale
        Metabolic Model). The GEMs are available through tools like GEM Browser,
        Map Viewer and Interaction Partners. The result is returned in JSON format.<br /><br />
        Required parameters: GEM name (e.g. **Human-GEM**) "
      operationId: "integratedModelInfo"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /compartments/{id}?model={model}:
    get:
      tags:
      - "Compartments"
      summary: "Get information for a given compartment."
      description: "Retrieve all containing metabolites, genes, reactions
        and subsystems for a given compartment. The result is returned in JSON format. <br /><br />
        Required parameters: compartment ID (e.g. **golgi_apparatus**) and
        model name (e.g. **HumanGem**) "
      operationId: "compartmentInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /compartments/{id}/related-reactions?model={model}:
    get:
      tags:
      - "Compartments"
      summary: "Get related reactions for a given compartment."
      description: "Retrieve all related reactions for a given compartment. The
        result is returned in JSON format. <br /><br />
        Required parameters: compartment ID (e.g. **golgi_apparatus**) and
        model name (e.g. **HumanGem**) "
      operationId: "compartmentRelatedReactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /genes/{id}?model={model}:
    get:
      tags:
      - "Genes"
      summary: "Get information for a given gene."
      description: "Retrieve all information for a given gene. The result is
        returned in JSON format. <br /><br />
        Required parameters: gene ID (e.g.  **ENSG00000196502**)
        and model name (e.g. **HumanGem**)"
      operationId: "geneInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /genes/{id}/related-reactions?model={model}:
    get:
      tags:
      - "Genes"
      summary: "Get related reations for a given gene."
      description: "Retrieve all related reactions for a given gene. The result is
        returned in JSON format. <br /><br />
        Required parameters: gene ID (e.g.  **ENSG00000196502**)
        and model name (e.g. **HumanGem**)"
      operationId: "geneRelatedReactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}?model={model}:
    get:
      tags:
      - "Metabolites"
      summary: "Get information for a given metabolite."
      description: "Retrieve all information related to a given metabolite. The
        result is returned in JSON format. <br /><br />
        Required parameters: metabolite ID (e.g. **m01587m**) and model name (e.g. **HumanGem**)"
      operationId: "metaboliteInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}/related-reactions?model={model}:
    get:
      tags:
      - "Metabolites"
      summary: "Get related reactions for a given metabolite."
      description: "Retrieve all related reactions for a given metabolite. The
        returned result is in JSON format.  <br /><br />
        Required parameters: metabolite ID (e.g. **m01587m**) and model name (e.g. **HumanGem**)"
      operationId: "metaboliteRelatedReactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}/related-metabolites?model={model}:
    get:
      tags:
      - "Metabolites"
      summary: "Get related metabolites for a given metabolite."
      description: "Retrieve all related metabolites involving a given
        metabolite. The returned result is in JSON format.  <br /><br />
        Required parameters: metabolite ID (e.g. **m01587m**) and model name (e.g. **HumanGem**)"
      operationId: "metaboliteRelatedMetaboliteInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /reactions/{id}?model={model}:
    get:
      tags:
      - "Reactions"
      summary: "Get information for a given reaction."
      description: "Retrieve all information we have on a reaction. The
        returned result is in JSON format. <br /><br />
        Required parameters: reaction ID (e.g.  **HMR_3000**) and model name (e.g. **HumanGem**)"
      operationId: "reactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /reactions/{id}/related-reactions?model={model}:
    get:
      tags:
      - "Reactions"
      summary: "Get related reactions involving a given reaction."
      description: "Retrieve all related reactions involving a given reaction.
        The returned result is in JSON format. <br /><br />
        Required parameters: reaction ID (e.g.  **HMR_3000**) and model name (e.g. **HumanGem**)"
      operationId: "reactionRelatedReactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /subsystems/{id}?model={model}:
    get:
      tags:
      - "Subsystems"
      summary: "Get information for a given subsystem."
      description: "Retrieve all information (including metabolites,
        compartments and genes) for a given subsystem. The returned result is in
        JSON format. <br /><br />
        Required parameters: subsystem ID (e.g.  **eicosanoid_metabolism**) and
        model name (e.g. **HumanGem**)"
      operationId: "subsystemInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /subsystems/{id}/related-reactions?model={model}:
    get:
      tags:
      - "Subsystems"
      summary: "Get related reactions for a given subsystem."
      description: "Retrieve all related reactions for a given subsystem. The
        returned result is in JSON format. <br /><br />
        Required parameters: subsystem ID (e.g.  **eicosanoid_metabolism**) and
        model name (e.g. **HumanGem**)"
      operationId: "subsystemRelatedReactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /interaction-partners/{id}?model={model}:
    get:
      tags:
      - "Interaction Partners"
      summary: "Get interaction partners for a given gene."
      description: "Retrieve all first order interaction partners for a given
        gene. The returned result is in JSON format. <br /><br />
        Required parameters: gene ID (e.g.  **ENSG00000196502**) and model name (e.g. **HumanGem**)"
      operationId: "geneInteractionPartners"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "model"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /maps/listing:
    get:
      tags:
      - "Miscellaneous"
      summary: "List all compartments and subsystems."
      description: "Retrieve a list of all compartments and subsystems that are
        available on Metabolic Atlas. The returned result is in JSON format. <br /><br />
        Required parameters: None"
      operationId: "mapListing"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /random-components:
    get:
      tags:
      - "Miscellaneous"
      summary: "Get information for random components."
      description: "Retrieve information for a number of random genes,
        metabolites, compartments, reactions and subsystems. The
        returned result is in JSON format. <br /><br />
        Required parameters: None"
      operationId: "randomComponentInfo"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
