swagger: "2.0"
info:
  description: "Metabolite Atlas can be accessed programmatically using this web API. Here we provide endpoints to get global information on the list of models integrated in Metabolic Atlas and to retrieve bulk or details information on those models. The API is still under developpment and might change without notice.\n\nUse model.short_name attribute (e.g. \"Yeast-GEM\", \"Human-GEM\") or model.database attribute as model parameter."
  version: "2.0"
  title: "Metabolic Atlas API"
  termsOfService: "https://metabolicatlas.org/about"
  contact:
    email: "contact@metabolicatlas.org"
  license:
    name: "GPL version 3"
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
basePath: "/api/v2"
tags:
- name: "Integrated models"
- name: "Compartments"
- name: "Genes"
- name: "Metabolites"
- name: "Reactions"
- name: "Subsystems"
- name: "Interaction Partners"
- name: "miscellaneous"
paths:
  /repository/integrated_models:
    get:
      tags:
      - "Integrated models"
      summary: "List all Genome-scale metabolic models (GEMs) that are available on the GEM browser."
      description: "List all Genome-scale metabolic models (GEMs) that are available on the GEM browser."
      operationId: "integratedModels"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
  /repository/integrated_models/{name}:
    get:
      tags:
      - "Integrated models"
      summary: "List all information for a given model available on the GEM browser, supply its name e.g., 'Human-GEM'."
      description: "List all information for a given model available on the GEM browser, supply its name e.g., 'Human-GEM'."
      operationId: "modelInfo"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /compartments/{id}:
    get:
      tags:
      - "Compartments"
      summary: "For a given compartment name (e.g., Golgi apparatus or
        golgi_apparatus), returns all containing metabolites, genes, reactions
        and subsystems."
      description: "For a given compartment name (e.g., Golgi apparatus or
        golgi_apparatus), returns all containing metabolites, genes, reactions
        and subsystems."
      operationId: "compartmentInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /compartments/{id}/related-reactions:
    get:
      tags:
      - "Compartments"
      summary: "For a given compartment name (e.g., Golgi apparatus or
        golgi_apparatus), return all reactions involving this compartment."
      description: "For a given compartment name (e.g., Golgi apparatus or
        golgi_apparatus), return all reactions involving this compartment."
      operationId: "compartmentInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /genes/{id}:
    get:
      tags:
      - "Genes"
      summary: "List all information for a given gene (for example ENSG00000196502 or SULT1A1)."
      description: "List all information for a given gene (for example ENSG00000196502 or SULT1A1)."
      operationId: "geneInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /genes/{id}/related-reactions:
    get:
      tags:
      - "Genes"
      summary: "List all reactions for a given gene (for example ENSG00000196502 or SULT1A1)."
      description: "List all reactions for a given gene (for example ENSG00000196502 or SULT1A1)."
      operationId: "geneInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}:
    get:
      tags:
      - "Metabolites"
      summary: "List all information for a given metabolite (for example m01587m or citrate[m])."
      description: "List all information for a given metabolite (for example m01587m or citrate[m])."
      operationId: "metaboliteInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}/related-reactions:
    get:
      tags:
      - "Metabolites"
      summary: "List all reactions for a given metabolite (for example m01587m or citrate[m])."
      description: "List all reactions for a given metabolite (for example m01587m or citrate[m])."
      operationId: "metaboliteInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}/related-metabolites:
    get:
      tags:
      - "Metabolites"
      summary: "List all related metabolites for involving a given metabolite (for example m01587m or citrate[m])."
      description: "List all related metabolites involving a given metabolite (for example m01587m or citrate[m])."
      operationId: "metaboliteInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /reactions/{id}:
    get:
      tags:
      - "Reactions"
      summary: "List all the information we have on a reaction (for example HMR_3905)."
      description: "List all the information we have on a reaction (for example HMR_3905)."
      operationId: "reactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /reactions/{id}/related-reactions:
    get:
      tags:
      - "Reactions"
      summary: "List all related reactions involving a given reaction (for example HMR_3905)."
      description: "List all related reactions involving a given reaction (for example HMR_3905)."
      operationId: "reactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /subsystems/{id}:
    get:
      tags:
      - "Subsystems"
      summary: "For a given subsystem name (e.g. eicosanoid_metabolism), list all the containing metabolites and genes/genes."
      description: "For a given subsystem name (e.g. eicosanoid_metabolism), list all the containing metabolites and genes/genes."
      operationId: "subsystemInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /subsystems/{id}/related-reactions:
    get:
      tags:
      - "Subsystems"
      summary: "For a given subsystem name (e.g. eicosanoid_metabolism), list all the containing reactions."
      description: "For a given subsystem name (e.g. eicosanoid_metabolism), list all the containing reactions."
      operationId: "subsystemInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /interaction-partners/{id}/:
    get:
      tags:
      - "Interaction Partners"
      summary: "List all first order interaction partners for a given gene (e.g. ENSG00000196502 or SULT1A1)."
      description: "List all first order interaction partners for a given gene (e.g. ENSG00000196502 or SULT1A1)."
      operationId: "geneInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /maps/listing:
    get:
      tags:
      - "miscellaneous"
      summary: "List all compartments and subsystems."
      description: "List all compartments and subsystems."
      operationId: "mapListingInfo"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /random-components:
    get:
      tags:
      - "miscellaneous"
      summary: "List all information for random genes, metabolites compartments, reactions and subsystems."
      description: "List all information for random genes, metabolites compartments, reactions and subsystems."
      operationId: "randomComponentInfo"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
