swagger: "2.0"
info:
  description: "Metabolite Atlas can be accessed programmatically using this web API. Here we provide endpoints to get global information on the list of models integrated in Metabolic Atlas and to retrieve bulk or details information on those models. The API is still under developpment and might change without notice.\n\nUse model.short_name attribute (e.g. \"Yeast-GEM\", \"Human-GEM\") or model.database attribute as model parameter."
  version: "2.0"
  title: "Metabolic Atlas API"
  termsOfService: "https://metabolicatlas.org/about"
  contact:
    email: "contact@metabolicatlas.org"
  license:
    name: "GPL version 3"
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
basePath: "/api/v2"
tags:
- name: "Integrated models"
- name: "Compartments"
- name: "Genes"
- name: "Metabolites"
- name: "Reactions"
- name: "Subsystems"
- name: "Interaction Partners"
- name: "Miscellaneous"
paths:
  /repository/integrated_models:
    get:
      tags:
      - "Integrated models"
      summary: "List all integrated GEMs."
      description: "Retrieve a list of all GEMs (Genome-Scale
        Metabolic Models) that Metabolic Atlas integrates. These GEMs are
        available through tools like GEM Browser, Map Viewer and Interaction
        Partners. The list is returned in JSON format. No parameters are
        required."
      operationId: "integratedModels"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
  /repository/integrated_models/{name}:
    get:
      tags:
      - "Integrated models"
      summary: "Get information of a given GEM."
      description: "Retrieve information for a given GEM (Genome-Scale
        Metabolic Model). The GEMs are available through tools like GEM Browser,
        Map Viewer and Interaction Partners. The result is returned in JSON format.
        Required parameter: GEM name, e.g. **Human-GEM** "
      operationId: "modelInfo"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /compartments/{id}:
    get:
      tags:
      - "Compartments"
      summary: "Get information of a given compartment."
      description: "Retrieve all containing metabolites, genes, reactions
        and subsystems for a given compartment. The result is returned in JSON format.
        Required parameter: compartment ID, e.g. **golgi_apparatus** "
      operationId: "compartmentInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /compartments/{id}/related-reactions:
    get:
      tags:
      - "Compartments"
      summary: "Get related reactions for a given compartment."
      description: "Retrieve all related reactions for a given compartment. The
        result is returned in JSON format. Required parameter: compartment ID,
        e.g. **golgi_apparatus** "
      operationId: "compartmentReaction"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /genes/{id}:
    get:
      tags:
      - "Genes"
      summary: "Get information of a given gene."
      description: "Retrieve all information for a given gene. The result is
        returned in JSON format. Required parameter: gene ID, e.g.
        **ENSG00000196502** or **Sult1a1**"
      operationId: "geneInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /genes/{id}/related-reactions:
    get:
      tags:
      - "Genes"
      summary: "Get related reations for a given gene."
      description: "Retrieve all related reactions for a given gene. The result is
        returned in JSON format. Required parameter: gene ID, e.g.
        **ENSG00000196502** or **Sult1a1**"
      operationId: "geneReaction"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}:
    get:
      tags:
      - "Metabolites"
      summary: "Get information of a given metabolite."
      description: "Retrieve all information related to a given metabolite. The
        result is returned in JSON format. Required parameter: metabolite ID,
        e.g. **m01587m**"
      operationId: "metaboliteInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}/related-reactions:
    get:
      tags:
      - "Metabolites"
      summary: "Get related reactions for a given metabolite."
      description: "Retrieve all related reactions for a given metabolite. The
        returned result is in JSON format. Required parameter: metabolite ID,
        e.g. **m01587m**"
      operationId: "metaboliteReaction"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /metabolites/{id}/related-metabolites:
    get:
      tags:
      - "Metabolites"
      summary: "Get related metabolites for a given metabolite."
      description: "Retrieve all related metabolites involving a given
        metabolite. The returned result is in JSON format. Required parameter:
        metabolite ID, e.g. **m01587m**"
      operationId: "metaboliteRelatedMetabolite"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /reactions/{id}:
    get:
      tags:
      - "Reactions"
      summary: "Get information of a given reaction."
      description: "Retrieve all information we have on a reaction. The
        returned result is in JSON format. Required parameter: reaction ID, e.g.
        **HMR_3000**"
      operationId: "reactionInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /reactions/{id}/related-reactions:
    get:
      tags:
      - "Reactions"
      summary: "Get related reactions involving a given reaction."
      description: "Retrieve all related reactions involving a given reaction.
        The returned result is in JSON format. Required parameter: reaction ID,
        e.g. **HMR_3000**"
      operationId: "reactionRelatedReaction"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /subsystems/{id}:
    get:
      tags:
      - "Subsystems"
      summary: "Get information for a given subsystem."
      description: "Retrieve all information (including metabolites,
        compartments and genes) for a given subsystem. The returned result is in
        JSON format. Required parameter: subsystem ID, e.g.
        **eicosanoid_metabolism** "
      operationId: "subsystemInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /subsystems/{id}/related-reactions:
    get:
      tags:
      - "Subsystems"
      summary: "Get related reactions for a given subsystem."
      description: "Retrieve all related reactions for a given subsystem. The
        returned result is in JSON format. Required parameter: subsystem ID, e.g.
        **eicosanoid_metabolism** "
      operationId: "subsystemRelatedReaction"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /interaction-partners/{id}/:
    get:
      tags:
      - "Interaction Partners"
      summary: "List all first order interaction partners for a given gene (e.g. ENSG00000196502 or SULT1A1)."
      description: "List all first order interaction partners for a given gene (e.g. ENSG00000196502 or SULT1A1)."
      operationId: "geneInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /maps/listing:
    get:
      tags:
      - "Miscellaneous"
      summary: "List all compartments and subsystems."
      description: "List all compartments and subsystems."
      operationId: "mapListingInfo"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
  /random-components:
    get:
      tags:
      - "Miscellaneous"
      summary: "List all information for random genes, metabolites compartments, reactions and subsystems."
      description: "List all information for random genes, metabolites compartments, reactions and subsystems."
      operationId: "randomComponentInfo"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful operation"
        "404":
          description: "Invalid input"
